const USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED';

// title validation
const TITLE_FORBIDDEN_WORD = 'TITLE_FORBIDDEN_WORD';
const TITLE_INVALID_LENGTH = 'TITLE_INVALID_LENGTH';

// description validation
const DESCRIPTION_FORBIDDEN_WORD = 'DESCRIPTION_FORBIDDEN_WORD';
const DESCRIPTION_INVALID_LENGTH = 'DESCRIPTION_INVALID_LENGTH';

// funding_target validation
const FUNDING_TARGET_INVALID_NUMBER = 'FUNDINGTARGET_INVALID_NUMBER';
const FUNDING_TARGET_INVALID_VALUE = 'FUNDINGTARGET_INVALID_VALUE';

const SERVER_UNKNOWN_ERROR = 'SERVER_UNKNOWN_ERROR';
const REGISTRATION_USER_ALREADY_EXISTS = 'REGISTRATION_USER_ALREADY_EXISTS';
const LOGIN_INVALID = 'LOGIN_INVALID';

// email validation
const EMAIL_FORBIDDEN_WORD = 'EMAIL_FORBIDDEN_WORD';
const EMAIL_INVALID_STRING_FORMAT = 'EMAIL_INVALID_STRING_FORMAT';
const EMAIL_INVALID_LENGTH = 'EMAIL_INVALID_LENGTH';

// full_name validation
const FULL_NAME_FORBIDDEN_WORD = 'FULL_NAME_FORBIDDEN_WORD';
const FULL_NAME_INVALID_STRING_FORMAT = 'FULL_NAME_INVALID_STRING_FORMAT';
const FULL_NAME_INVALID_LENGTH = 'FULL_NAME_INVALID_LENGTH';

// password validation
const PASSWORD_INVALID_LENGTH = 'PASSWORD_INVALID_LENGTH';

const UNKNOWN_ERROR = 'UNKNOWN_ERROR';