 /*jshint esversion: 6*/
export const USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED';

// title validation
export const TITLE_FORBIDDEN_WORD = 'TITLE_FORBIDDEN_WORD';
export const TITLE_INVALID_LENGTH = 'TITLE_INVALID_LENGTH';

// description validation
export const DESCRIPTION_FORBIDDEN_WORD = 'DESCRIPTION_FORBIDDEN_WORD';
export const DESCRIPTION_INVALID_LENGTH = 'DESCRIPTION_INVALID_LENGTH';

export const SERVER_UNKNOWN_ERROR = 'SERVER_UNKNOWN_ERROR';
export const REGISTRATION_USER_ALREADY_EXISTS = 'REGISTRATION_USER_ALREADY_EXISTS';
export const LOGIN_INVALID = 'LOGIN_INVALID';

// email validation
export const EMAIL_FORBIDDEN_WORD = 'EMAIL_FORBIDDEN_WORD';
export const EMAIL_INVALID_STRING_FORMAT = 'EMAIL_INVALID_STRING_FORMAT';
export const EMAIL_INVALID_LENGTH = 'EMAIL_INVALID_LENGTH';

// full_name validation
export const FULL_NAME_FORBIDDEN_WORD = 'FULL_NAME_FORBIDDEN_WORD';
export const FULL_NAME_INVALID_STRING_FORMAT = 'FULL_NAME_INVALID_STRING_FORMAT';
export const FULL_NAME_INVALID_LENGTH = 'FULL_NAME_INVALID_LENGTH';

// password validation
export const PASSWORD_INVALID_LENGTH = 'PASSWORD_INVALID_LENGTH';

// donation validation
export const USER_DONATED_NEGATIVE_OR_ZERO_MONEY = 'USER_DONATED_NEGATIVE_OR_ZERO_MONEY';
export const WELL_DOES_NOT_EXIST = 'WELL_DOES_NOT_EXIST';
export const USER_NOT_ENOUGH_MONEY = 'USER_NOT_ENOUGH_MONEY';

// unknown error
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

